{{- $environment := .Values.environment | default dict }}
{{- if .Values.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: crabserver
  labels:
    env: k8s-{{$environment}}
    app: crabserver
  namespace: crab
data:
  entrypoint.sh: |
{{ (.Files.Get "scripts/entrypoint.sh" | indent 4) }}
  config.py: |
{{ (.Files.Get (printf "config/%s/config.py" $environment) | indent 4) }}
{{- end }}
