{{- $environment := .Values.environment | default dict }}
{{- if .Values.logPipeline.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: crab
  labels:
    app: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:8.1.3
        name: logstash
        env:
        - name: CMSWEB_CLUSTER
          {{- if (eq (toString $environment) "prod") }}
          value: prod
          {{- else if (eq (toString $environment) "preprod")}}
          value: testbed
          {{- else }}
          value: dev
          {{- end }}
        - name: CMSWEB_ENV
          {{- if (eq (toString $environment) "prod") }}
          value: prod
          {{- else if (eq (toString $environment) "preprod")}}
          value: testbed
          {{- else }}
          value: dev
          {{- end }}
        - name: LS_JAVA_OPTS
          value: "-Xms256m -Xmx4g"
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        - -e
        #- --log.level=debug # in k8s, output stdout prints only in debug
        resources:
          requests:
            memory: 512Mi
            cpu: "400m"
          limits:
            memory: 5Gi
            cpu: "4000m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml

{{- end }}
