{{- if .Values.logPipeline.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: crab
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  type: NodePort
  ports:
  - nodePort: 30044
    targetPort: 5044
    protocol: TCP
    port: 5044
{{- end }}
