apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archi-crab-staging-openwebui
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "6"}
spec:
  project: archi-crab
  source:
    repoURL: https://github.com/nausikt/CMSKubernetes.git
    targetRevision: archi-crab-testbed
    path: helm/archi-crab/openwebui
    helm: {valueFiles: [values-staging.yaml]}
  destination: {server: https://kubernetes.default.svc, namespace: archi-crab-staging}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
