apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crab-svcs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # ---------- test2 cluster ----------
          - { svc: crabserver, env: test, cluster: test2 }
          # ---------- test12 cluster ----------
          - { svc: crabserver, env: test, cluster: test12 }
          # ---------- test14 cluster ----------
          - { svc: crabserver, env: test, cluster: test14 }
          # ---------- preprod cluster ----------
          # - { svc: crabserver, env: preprod, cluster: preprod }
  template:
    metadata:
      name: '{{svc}}-{{cluster}}'             # e.g., crabserver-test2
      labels:
        team: crab
        env: '{{env}}'
    spec:
      project: project-crab
      source:
        repoURL: https://github.com/sinonkt/CMSKubernetes.git
        targetRevision: migrate-to-argocd
        path: helm/crabserver
        helm:
          valueFiles:
            - values.yaml
            - values-testx.yaml
      destination:
        name: cmsweb-{{cluster}}               # <-- Argo cluster name (registered via argocd cluster add e.g. cmsweb-test2, cmsweb-test12, ...etc)
        namespace: crab
      syncPolicy:
        automated: { prune: false, selfHeal: true }
        syncOptions: [ CreateNamespace=true ]

