apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crab-svcs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # ---------- test2 cluster ----------
          - { svc: crabserver, env: test2, cluster: cmsweb-test2, targetRevision: master, repoURL: "https://gitlab.cern.ch/crab3/crab-k8s-overlays.git" }
          
          # ---------- test12 cluster ----------
          - { svc: crabserver, env: test12, cluster: cmsweb-test12, targetRevision: master, repoURL: "https://gitlab.cern.ch/crab3/crab-k8s-overlays.git" }

          # ---------- test14 cluster ----------
          - { svc: crabserver, env: test14, cluster: cmsweb-test14, targetRevision: master, repoURL: "https://gitlab.cern.ch/crab3/crab-k8s-overlays.git" }
          
          # ---------- preprod cluster ----------
          # - { svc: crabserver, env: preprod, cluster: cmsweb-preprod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
          # - { svc: filebeat, env: preprod, cluster: cmsweb-preprod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
          # - { svc: logstash, env: preprod, cluster: cmsweb-preprod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
          
          # ---------- prod cluster ----------
          # - { svc: crabserver, env: prod, cluster: cmsweb-prod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
          # - { svc: filebeat, env: prod, cluster: cmsweb-prod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
          # - { svc: logstash, env: prod, cluster: cmsweb-prod, targetRevision: migrate-to-argocd, repoURL: "https://github.com/sinonkt/CMSKubernetes.git" }
  template:
    metadata:
      name: '{{svc}}-{{env}}'             # e.g., crabserver-test2
      labels:
        team: crab
        env: '{{env}}'
    spec:
      project: project-crab
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: argocd/apps/crab/{{svc}}/overlays/{{env}}
      destination:
        name: '{{cluster}}'               # <-- Argo cluster name (registered via argocd cluster add e.g. cmsweb-test2, cmsweb-test12, ...etc)
        namespace: crab
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ CreateNamespace=true ]

