apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: crabserver
  name: crabserver
  namespace: crab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crabserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-07T17:08:26+02:00"
        prometheus.io/port: "18270"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: crabserver
        env: k8s-test
    spec:
      containers:
        - args:
            - /data/run.sh
          command:
            - /bin/bash
            - /opt/config/entrypoint.sh
          env:
            - name: CRABSERVER_LOGSTDOUT
              value: t
            - name: CRABSERVER_THREAD_POOL
              value: "2"
          image: registry.cern.ch/cmscrab/crabserver:v3.250820-stable
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  cmsweb-ping --url=http://localhost:8270/crabserver/dev/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          name: crabserver
          ports:
            - containerPort: 8270
              name: crabserver
              protocol: TCP
            - containerPort: 18270
              name: crabserver-mon
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  cmsweb-ping --url=http://localhost:8270/crabserver/dev/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
            failureThreshold: 3
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 1500m
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/proxy
              name: proxy-secrets
              readOnly: true
            - mountPath: /etc/secrets
              name: secrets
              readOnly: true
            - mountPath: /etc/robots
              name: robot-secrets
              readOnly: true
            - mountPath: /etc/hmac
              name: hmac-secrets
              readOnly: true
            - mountPath: /host/etc/grid-security
              name: etc-grid-security
              readOnly: true
            - mountPath: /opt/config
              name: config
            - mountPath: /etc/token
              name: token-secrets
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
        - name: proxy-secrets
          secret:
            defaultMode: 420
            secretName: proxy-secrets
        - name: secrets
          secret:
            defaultMode: 420
            secretName: crabserver-secrets
        - name: robot-secrets
          secret:
            defaultMode: 420
            secretName: robot-secrets
        - name: hmac-secrets
          secret:
            defaultMode: 420
            secretName: hmac-secrets
        - hostPath:
            path: /etc/grid-security
            type: ""
          name: etc-grid-security
        - configMap:
            defaultMode: 420
            name: crabserver
          name: config
        - name: token-secrets
          secret:
            defaultMode: 420
            secretName: token-secrets
