apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount }}
  namespace: {{ .Values.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: woger
  namespace: {{ .Values.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
spec:
  address: {{ .Values.vault.address | quote }}
  caCertSecretRef: {{ .Values.vault.caSecret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: archi-crab
  namespace: {{ .Values.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
spec:
  vaultConnectionRef: woger
  method: kubernetes
  mount: {{ .Values.vault.authMount }}
  kubernetes:
    role: {{ .Values.vault.role }}
    serviceAccount: {{ .Values.vault.serviceAccount }}
    audiences: [{{ .Values.vault.audience | quote }}]
