{{- range $s := .Values.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $s.name }}
  namespace: {{ $.Values.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "1"}
spec:
  vaultAuthRef: archi-crab
  mount: {{ $.Values.vault.mount }}
  type: kv-v2
  path: {{ $.Values.vault.pathPrefix }}/{{ $s.path }}
  refreshAfter: {{ $.Values.refreshAfter }}
  destination:
    name: {{ $s.name }}
    create: true
{{- end }}
