apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: crabserver
  files:
    - config/config.py
    - config/entrypoint.sh
