apiVersion: v1
kind: Service
metadata:
  name: crabserver
  namespace: crab
spec:
  type: ClusterIP
  selector:
    app: crabserver
  ports:
    - name: crabserver
      port: 8270
    - name: crabserver-mon
      port: 18270
