apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crab

resources:
  - ../../base
  - filebeat-daemonset.yaml

configMapGenerator:
- name: filebeat-crab-config
  files:
    - config/filebeat.yml
  options:
    disableNameSuffixHash: true
